apiVersion: v1
kind: Service
metadata:
  name: lyric2vec-api-service
  labels:
    app: lyric2vec-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: lyric2vec-api

---
# Optional: NodePort for external access
apiVersion: v1
kind: Service
metadata:
  name: lyric2vec-api-nodeport
  labels:
    app: lyric2vec-api
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: lyric2vec-api
