apiVersion: apps/v1
kind: Deployment
metadata:
  name: lyric2vec-api
  labels:
    app: lyric2vec-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lyric2vec-api
  template:
    metadata:
      labels:
        app: lyric2vec-api
    spec:
      containers:
        - name: api
          image: lyric2vec-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: API_PORT
              value: "8080"
            - name: API_HOST
              value: "0.0.0.0"
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: artifacts
              mountPath: /app/data/artifacts
              readOnly: true
            - name: models
              mountPath: /app/models
              readOnly: true
      volumes:
        - name: artifacts
          persistentVolumeClaim:
            claimName: lyric2vec-artifacts
        - name: models
          persistentVolumeClaim:
            claimName: lyric2vec-models

---
# Optional: Horizontal Pod Autoscaler
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: lyric2vec-api-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: lyric2vec-api
#   minReplicas: 2
#   maxReplicas: 10
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70
